--- 
jobs: 
  - job: "Tip all recent matches and submit"
    pool: 
      maxParallel: 1
      strategy: 
        matrix: 
          Python37: 
            python.version: "3.7"
      vmImage: vs2017-win2016
    steps: 
      - inputs: 
          architecture: x64
          versionSpec: $(python.version)
        task: UsePythonVersion@0
      - script: "pip install selenium && npm install chromedriver"
        displayName: "Install dependencies"

      - powershell: "python3 TipBot.py"
        displayName: "Run tipping bot."
schedules:
    always: true
    branches: 
      include: 
        - master
    cron: "0 12 * * 4"
    displayName: "Weekly Thursday build"
 
trigger: 
  - master
